# Alacritty Configuration File

[window]
opacity = 1.0
option_as_alt = "Both"

[window.padding]
x = 24
y = 24

[font]
normal.family = "MesloLGS NF"
normal.style = "Regular"
size = 14 # Adjust based on platform, default is set for macOS (Darwin)

[cursor]
style = "Block"

[colors.primary]
background = "0x1f2528"
foreground = "0xc0c5ce"

[colors.normal]
black = "0x1f2528"
red = "0xec5f67"
green = "0x99c794"
yellow = "0xfac863"
blue = "0x6699cc"
magenta = "0xc594c5"
cyan = "0x5fb3b3"
white = "0xc0c5ce"

[colors.bright]
black = "0x65737e"
red = "0xec5f67"
green = "0x99c794"
yellow = "0xfac863"
blue = "0x6699cc"
magenta = "0xc594c5"
cyan = "0x5fb3b3"
white = "0xd8dee9"

[[keyboard.bindings]]
key = "s"
mods = "Command"
chars = "\\u001b[3;4s"

[[keyboard.bindings]]
key = "b"
mods = "Command"
chars = "\\u001b[3;4b"

[[keyboard.bindings]]
key = "i"
mods = "Command"
chars = "\\u001b[3;4i"

[[keyboard.bindings]]
key = "LBracket"
mods = "Command"
chars = "\\u001b[3;4["

[[keyboard.bindings]]
key = "RBracket"
mods = "Command"
chars = "\\u001b[3;4]"

