#!/usr/bin/env python3
import os
import sys
import webbrowser
from pathlib import Path


from config.io import load_raw_config_file
from config.processor import validate_config, parse_config
from tui.formatters import clean_issue_key

from commands.upsert import execute_upsert
from commands.comment import execute_comment
from commands.assign import execute_assign
from commands.branch import execute_branch
from commands.transition import execute_transition
from commands.list import execute_list
from commands.export import execute_export

CONFIG_DIR = os.path.expanduser("~/.config/ihj")
CACHE_DIR = os.path.expanduser("~/.local/state/ihj")
EXECUTABLE = sys.argv[0]


def main():
    Path(CONFIG_DIR).mkdir(parents=True, exist_ok=True)
    Path(CACHE_DIR).mkdir(parents=True, exist_ok=True)

    try:
        raw_cfg = load_raw_config_file(f"{CONFIG_DIR}/config.yaml")
        validate_config(raw_cfg)
        cfg = parse_config(raw_cfg)
    except Exception as e:
        sys.exit(f"Setup Error: {e}")

    server = cfg.get("server")
    token = os.environ.get("JIRA_BEARER_TOKEN")
    if not token:
        sys.exit("Error: JIRA_BEARER_TOKEN environment variable not set.")

    args = sys.argv[1:]
    use_toast = "--toast" in args
    clean_args_bg = [a for a in args if a != "--toast"]

    # --- Routing Logic ---

    if "--edit" in args or "--create" in args:
        execute_upsert(args, CACHE_DIR, server, token, cfg)
        sys.exit(0)

    if "--comment" in args:
        execute_comment(args, server, token, cfg)
        sys.exit(0)

    if "--assign" in args:
        execute_assign(clean_args_bg, CACHE_DIR, server, token, use_toast)
        sys.exit(0)

    if "--branch" in args:
        execute_branch(clean_args_bg, CACHE_DIR, use_toast)
        sys.exit(0)

    if "--transition" in args:
        execute_transition(clean_args_bg, server, token, cfg)
        sys.exit(0)

    if "--open" in args:
        clean_key = clean_issue_key(clean_args_bg[-1])
        webbrowser.open(f"{server}/browse/{clean_key}")
        sys.exit(0)

    if "--export" in args:
        execute_export(clean_args_bg, server, token, cfg)
        sys.exit(0)

    execute_list(args, CACHE_DIR, EXECUTABLE, server, token, cfg)


if __name__ == "__main__":
    main()
