[tools]
# global tool versions go here

deno = 'latest'
go = 'latest'
gradle = 'latest'
java = "corretto-21"
julia = 'latest'
kind = 'latest'
kubectl = 'latest'
kustomize = 'latest'
helm = 'latest'
lua = '5.1'
node = 'lts'
pnpm = 'latest'
python = "latest"
quarkus = 'latest'
scala = 'latest'
terraform = 'latest'

[settings]

legacy_version_file = true

always_keep_download = false # deletes downloads after install
always_keep_install = false  # deletes an install on a failure
